# Generated by Django 4.2.6 on 2023-10-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('DROPPED', 'DROPPED')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
