# Generated by Django 4.2.6 on 2023-10-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_alter_status_status_alter_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('МЕСТ НЕТ', 'МЕСТ НЕТ'), ('ДОСТУПНО', 'ДОСТУПНО')], max_length=10, unique=True),
        ),
    ]
